/****************************************************************************************************
 * Copyright (C) 2017-2019 FengYunChuanShuo
 * 
 * Autogenerated module gettters
 * In order to use ObjectManager, all game object should derive from LObject.
 * 
 * Author:   Y.Moon <chglove@live.cn>
 * Version:  0.4
 * Created:  2019-05-08
 * 
 ***************************************************************************************************/

public abstract partial class LogicObject
{
    #region Module getters

    protected static Session session { get; private set; }
    protected static Module_Active moduleActive { get; private set; }
    protected static Module_AI moduleAI { get; private set; }
    protected static Module_Announcement moduleAnnouncement { get; private set; }
    protected static Module_AnswerOption moduleAnswerOption { get; private set; }
    protected static Module_Assist moduleAssist { get; private set; }
    protected static Module_Attribute moduleAttribute { get; private set; }
    protected static Module_Avatar moduleAvatar { get; private set; }
    protected static Module_Awake moduleAwake { get; private set; }
    protected static Module_AwakeMatch moduleAwakeMatch { get; private set; }
    protected static Module_Battle moduleBattle { get; private set; }
    protected static Module_Bordlands moduleBordlands { get; private set; }
    protected static Module_Cangku moduleCangku { get; private set; }
    protected static Module_Charge moduleCharge { get; private set; }
    protected static Module_Chase moduleChase { get; private set; }
    protected static Module_Chat moduleChat { get; private set; }
    protected static Module_Collection moduleCollection { get; private set; }
    protected static Module_DatingGift moduleDatingGift { get; private set; }
    protected static Module_Equip moduleEquip { get; private set; }
    protected static Module_FactionBattle moduleFactionBattle { get; private set; }
    protected static Module_Forging moduleForging { get; private set; }
    protected static Module_Friend moduleFriend { get; private set; }
    protected static Module_Furnace moduleFurnace { get; private set; }
    protected static Module_GameGuard moduleGameGuard { get; private set; }
    protected static Module_Gift moduleGift { get; private set; }
    protected static Module_GiftDating moduleGiftDating { get; private set; }
    protected static Module_Global moduleGlobal { get; private set; }
    protected static Module_Gm moduleGm { get; private set; }
    protected static Module_Guide moduleGuide { get; private set; }
    protected static Module_Home moduleHome { get; private set; }
    protected static Module_Labyrinth moduleLabyrinth { get; private set; }
    protected static Module_Loading moduleLoading { get; private set; }
    protected static Module_Login moduleLogin { get; private set; }
    protected static Module_Mailbox moduleMailbox { get; private set; }
    protected static Module_Match moduleMatch { get; private set; }
    protected static Module_Notice moduleNotice { get; private set; }
    protected static Module_Npc moduleNpc { get; private set; }
    protected static Module_NPCDating moduleNPCDating { get; private set; }
    protected static Module_NPCDatingSettlement moduleNPCDatingSettlement { get; private set; }
    protected static Module_NpcGaiden moduleNpcGaiden { get; private set; }
    protected static Module_Pet modulePet { get; private set; }
    protected static Module_Player modulePlayer { get; private set; }
    protected static Module_PVE modulePVE { get; private set; }
    protected static Module_PVEEvent modulePVEEvent { get; private set; }
    protected static Module_PVP modulePVP { get; private set; }
    protected static Module_Rune moduleRune { get; private set; }
    protected static Module_SelectRole moduleSelectRole { get; private set; }
    protected static Module_Set moduleSet { get; private set; }
    protected static Module_Shop moduleShop { get; private set; }
    protected static Module_Skill moduleSkill { get; private set; }
    protected static Module_Story moduleStory { get; private set; }
    protected static Module_Task moduleTask { get; private set; }
    protected static Module_Team moduleTeam { get; private set; }
    protected static Module_Union moduleUnion { get; private set; }
    protected static Module_Welfare moduleWelfare { get; private set; }
    protected static Module_Wish moduleWish { get; private set; }

    private static bool m_modulesCreated = false;

    /// <summary>
    /// Internal function, do not call this function manually.
    /// Create all module instances.
    /// </summary>
    public static void CreateModules()
    {
        if (m_modulesCreated) return;
        m_modulesCreated = true;
    
        session = Module.Create<Session>("session");
        moduleActive = Module.Create<Module_Active>("module_active");
        moduleAI = Module.Create<Module_AI>("module_ai");
        moduleAnnouncement = Module.Create<Module_Announcement>("module_announcement");
        moduleAnswerOption = Module.Create<Module_AnswerOption>("module_answerOption");
        moduleAssist = Module.Create<Module_Assist>("module_assist");
        moduleAttribute = Module.Create<Module_Attribute>("module_attribute");
        moduleAvatar = Module.Create<Module_Avatar>("module_avatar");
        moduleAwake = Module.Create<Module_Awake>("module_awake");
        moduleAwakeMatch = Module.Create<Module_AwakeMatch>("module_awakeMatch");
        moduleBattle = Module.Create<Module_Battle>("module_battle");
        moduleBordlands = Module.Create<Module_Bordlands>("module_bordlands");
        moduleCangku = Module.Create<Module_Cangku>("module_cangku");
        moduleCharge = Module.Create<Module_Charge>("module_charge");
        moduleChase = Module.Create<Module_Chase>("module_chase");
        moduleChat = Module.Create<Module_Chat>("module_chat");
        moduleCollection = Module.Create<Module_Collection>("module_collection");
        moduleDatingGift = Module.Create<Module_DatingGift>("module_datingGift");
        moduleEquip = Module.Create<Module_Equip>("module_equip");
        moduleFactionBattle = Module.Create<Module_FactionBattle>("module_factionBattle");
        moduleForging = Module.Create<Module_Forging>("module_forging");
        moduleFriend = Module.Create<Module_Friend>("module_friend");
        moduleFurnace = Module.Create<Module_Furnace>("module_furnace");
        moduleGameGuard = Module.Create<Module_GameGuard>("module_gameGuard");
        moduleGift = Module.Create<Module_Gift>("module_gift");
        moduleGiftDating = Module.Create<Module_GiftDating>("module_giftDating");
        moduleGlobal = Module.Create<Module_Global>("module_global");
        moduleGm = Module.Create<Module_Gm>("module_gm");
        moduleGuide = Module.Create<Module_Guide>("module_guide");
        moduleHome = Module.Create<Module_Home>("module_home");
        moduleLabyrinth = Module.Create<Module_Labyrinth>("module_labyrinth");
        moduleLoading = Module.Create<Module_Loading>("module_loading");
        moduleLogin = Module.Create<Module_Login>("module_login");
        moduleMailbox = Module.Create<Module_Mailbox>("module_mailbox");
        moduleMatch = Module.Create<Module_Match>("module_match");
        moduleNotice = Module.Create<Module_Notice>("module_notice");
        moduleNpc = Module.Create<Module_Npc>("module_npc");
        moduleNPCDating = Module.Create<Module_NPCDating>("module_npcDating");
        moduleNPCDatingSettlement = Module.Create<Module_NPCDatingSettlement>("module_npcDatingSettlement");
        moduleNpcGaiden = Module.Create<Module_NpcGaiden>("module_npcGaiden");
        modulePet = Module.Create<Module_Pet>("module_pet");
        modulePlayer = Module.Create<Module_Player>("module_player");
        modulePVE = Module.Create<Module_PVE>("module_pve");
        modulePVEEvent = Module.Create<Module_PVEEvent>("module_pveEvent");
        modulePVP = Module.Create<Module_PVP>("module_pvp");
        moduleRune = Module.Create<Module_Rune>("module_rune");
        moduleSelectRole = Module.Create<Module_SelectRole>("module_selectRole");
        moduleSet = Module.Create<Module_Set>("module_set");
        moduleShop = Module.Create<Module_Shop>("module_shop");
        moduleSkill = Module.Create<Module_Skill>("module_skill");
        moduleStory = Module.Create<Module_Story>("module_story");
        moduleTask = Module.Create<Module_Task>("module_task");
        moduleTeam = Module.Create<Module_Team>("module_team");
        moduleUnion = Module.Create<Module_Union>("module_union");
        moduleWelfare = Module.Create<Module_Welfare>("module_welfare");
        moduleWish = Module.Create<Module_Wish>("module_wish");

        var modules = ObjectManager.GetAll<Module>();
        foreach (var module in modules) module.Initialize();
    }

    #endregion
}
